Upgrade to NXP LS-5.15.71-2.2.0
This is a minimum viable prerelease that can boot into Linux on second
silicon version of LX2160A and Clearfog-CX/Honeycomb carrier boards.

Major features and functional toptimisations are still missing, such as:
- retimer
- qsfp
- large pci bars
- improved pci device detection
- runtime switching of serdes speed
- persistent mac addresses from eeprom
- lx2162 som

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,26 +1,41 @@
-# use debian base
-FROM python:slim-buster
+FROM python:slim-bullseye
+
+# enable backports
+RUN printf "deb http://deb.debian.org/debian bullseye-backports main\n" >> /etc/apt/sources.list
+
+# retry at least 3 times to succeed on sketchy connections
+RUN printf 'Acquire::http { Proxy "%s"; };\n' $APTPROXY | tee -a /etc/apt/apt.conf.d/proxy
 
 # apt proxy (optional)
 ARG APTPROXY=
-RUN test -n "$APTPROXY" && printf 'Acquire::http { Proxy "%s"; }\n' $APTPROXY | tee -a /etc/apt/apt.conf.d/proxy || true
+RUN printf 'Acquire::Retries 3;\n' | tee -a /etc/apt/apt.conf.d/retry || true
 
 # prevent dpkg interactive dialogues
 ENV DEBIAN_FRONTEND=noninteractive
 
-# update
+# install updates
 RUN set -e; \
 	apt-get update; \
-	apt-get -y upgrade; \
+	apt-get upgrade -y; \
 	:
 
-RUN apt-get update ; apt-get -y install --no-install-recommends acpica-tools bc bison build-essential ca-certificates cpio debian-archive-keyring debootstrap device-tree-compiler dosfstools e2tools fakeroot file flex fuseext2 g++ gcc git kmod libncurses-dev libssl-dev libyaml-dev make meson mtools multistrap ninja-build p7zip p7zip-full pandoc parted pkg-config python python2 python3 qemu-system-arm rsync squashfs-tools sudo tar u-boot-tools unzip wget xz-utils yamllint
+# Install packages
+RUN set -e; \
+	apt-get update; \
+	apt-get --no-install-recommends -y install \
+		acpica-tools bc bison build-essential ca-certificates cmake cpio crossbuild-essential-arm64 debian-archive-keyring debootstrap device-tree-compiler dosfstools e2tools fakeroot fdisk file flex fuseext2 git kmod libncurses-dev libssl-dev libyaml-dev lzop make meson mtools ninja-build p7zip p7zip-full pandoc parted pkg-config rsync sudo tar u-boot-tools unzip wget xz-utils yamllint; \
+	apt-get --no-install-recommends -t bullseye-backports -y install qemu-system-arm; \
+	:
 
 RUN set -e; \
 	apt-get -y install --no-install-recommends libpython3-dev python3-pip python3-setuptools python3-wheel swig; \
 	pip3 install importlib-metadata; \
 	pip3 install dtschema; \
+	pip3 install cryptography; \
+	pip3 install pyelftools; \
 	:
+
+RUN apt-get install -y python3-pyelftools
 
 # build environment
 WORKDIR /work
