Test by Mor - new step structure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -127,109 +127,136 @@ jobs:
           recursive: true
 
   lava_test:
-      needs: [prepare_container, build_images]
-      runs-on: self-hosted
-      timeout-minutes: 90
-      env:
-        LAVA_SERVER: "192.168.15.184"
-        LAVA_PORT: "8001"
-        MINIO_SERVER: "192.168.15.201:8000"
-        BUCKET: "cipublish"
-        BUILD_TAG: "${{ needs.build_images.outputs.build_tag }}"
-        BUILD_COMMIT: "${{ needs.build_images.outputs.build_commit }}"
+  needs: [prepare_container, build_images]
+  runs-on: self-hosted
+  timeout-minutes: 90
+  env:
+    BUILD_COMMIT: "${{ needs.build_images.outputs.build_commit }}"
+  
+  steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Test Images on LAVA
+      uses: SolidRun/lava-test-definitions/.github/actions/lava-submit@main
+      with:
+        server: 192.168.15.184
+        port: 8001
+        timeout: 36000
+        jobs: |
+          [
+            {
+              "device_type": "lx2162a-solidrun",
+              "image_url": "https://solid-run-images.sos-de-fra-1.exo.io/LX2k/lx2160a_build/ls-6.6.52-2.2.0/2025-09-30_6e436bb/lx2162a_rev2_som_clearfog_multi_2000_650_2900_18_9_0-6e436bb.img.xz",
+              "compression": "xz",
+              "all_devices": false
+            }
+          ]
+
+  # lava_test:
+  #     needs: [prepare_container, build_images]
+  #     runs-on: self-hosted
+  #     timeout-minutes: 90
+  #     env:
+  #       LAVA_SERVER: "192.168.15.184"
+  #       LAVA_PORT: "8001"
+  #       MINIO_SERVER: "192.168.15.201:8000"
+  #       BUCKET: "cipublish"
+  #       BUILD_TAG: "${{ needs.build_images.outputs.build_tag }}"
+  #       BUILD_COMMIT: "${{ needs.build_images.outputs.build_commit }}"
       
-      steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #     steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Update LAVA Test Definitions
-        run: |
-          echo "try git pull."
-          response=$(curl -s -X POST "http://${LAVA_SERVER}:${LAVA_PORT}/git/pull")
-          echo "Response: $response"
+  #     - name: Update LAVA Test Definitions
+  #       run: |
+  #         echo "try git pull."
+  #         response=$(curl -s -X POST "http://${LAVA_SERVER}:${LAVA_PORT}/git/pull")
+  #         echo "Response: $response"
           
-          status=$(echo "$response" | jq -r '.status // empty')
-          if [ "$status" = "success" ]; then
-            echo "git pull done"
-          else
-            echo "ERROR: Failed to git pull test definitions"
-            echo "$response"
-            exit 1
-          fi
+  #         status=$(echo "$response" | jq -r '.status // empty')
+  #         if [ "$status" = "success" ]; then
+  #           echo "git pull done"
+  #         else
+  #           echo "ERROR: Failed to git pull test definitions"
+  #           echo "$response"
+  #           exit 1
+  #         fi
         
-      - name: Test LAVA API Connection
-        run: |
-          echo "Testing connection to LAVA API.."
-          curl -s "http://${LAVA_SERVER}:${LAVA_PORT}/health" || {
-            echo "ERROR: Cannot reach LAVA API"
-            exit 1
-          }
-          echo "LAVA server is reachable"
+  #     - name: Test LAVA API Connection
+  #       run: |
+  #         echo "Testing connection to LAVA API.."
+  #         curl -s "http://${LAVA_SERVER}:${LAVA_PORT}/health" || {
+  #           echo "ERROR: Cannot reach LAVA API"
+  #           exit 1
+  #         }
+  #         echo "LAVA server is reachable"
         
-      - name: Submit LAVA Job
-        id: submit
-        run: |
-          IMAGE_FILE="lx2162a_rev2_som_clearfog_multi_2000_650_2900_18_9_0-${BUILD_COMMIT}.img.xz"
-          #IMAGE_URL="http://${MINIO_SERVER}/${BUCKET}/${{ github.repository_id }}/${BUILD_TAG}/deploy/${IMAGE_FILE}"
-          IMAGE_URL="https://solid-run-images.sos-de-fra-1.exo.io/LX2k/lx2160a_build/ls-6.6.52-2.2.0/2025-09-30_6e436bb/lx2162a_rev2_som_clearfog_multi_2000_650_2900_18_9_0-6e436bb.img.xz"
+  #     - name: Submit LAVA Job
+  #       id: submit
+  #       run: |
+  #         IMAGE_FILE="lx2162a_rev2_som_clearfog_multi_2000_650_2900_18_9_0-${BUILD_COMMIT}.img.xz"
+  #         #IMAGE_URL="http://${MINIO_SERVER}/${BUCKET}/${{ github.repository_id }}/${BUILD_TAG}/deploy/${IMAGE_FILE}"
+  #         IMAGE_URL="https://solid-run-images.sos-de-fra-1.exo.io/LX2k/lx2160a_build/ls-6.6.52-2.2.0/2025-09-30_6e436bb/lx2162a_rev2_som_clearfog_multi_2000_650_2900_18_9_0-6e436bb.img.xz"
 
           
-          echo "Image URL: $IMAGE_URL"
+  #         echo "Image URL: $IMAGE_URL"
           
-          response=$(curl -s -X POST "http://${LAVA_SERVER}:${LAVA_PORT}/jobs/submit" \
-            -H "Content-Type: application/json" \
-            -d "{
-              \"device_type\": \"lx2162a-solidrun\",
-              \"image_url\": \"$IMAGE_URL\",
-              \"compression\": \"xz\",
-              \"all_devices\": false
-            }")
+  #         response=$(curl -s -X POST "http://${LAVA_SERVER}:${LAVA_PORT}/jobs/submit" \
+  #           -H "Content-Type: application/json" \
+  #           -d "{
+  #             \"device_type\": \"lx2162a-solidrun\",
+  #             \"image_url\": \"$IMAGE_URL\",
+  #             \"compression\": \"xz\",
+  #             \"all_devices\": false
+  #           }")
           
-          echo "Response: $response"
+  #         echo "Response: $response"
           
-          batch_id=$(echo "$response" | jq -r '.batch_id // empty')
-          if [ -z "$batch_id" ]; then
-            echo "ERROR: Failed to submit job"
-            exit 1
-          fi
+  #         batch_id=$(echo "$response" | jq -r '.batch_id // empty')
+  #         if [ -z "$batch_id" ]; then
+  #           echo "ERROR: Failed to submit job"
+  #           exit 1
+  #         fi
           
-          echo "Batch ID: $batch_id"
-          echo "batch_id=$batch_id" >> $GITHUB_OUTPUT
+  #         echo "Batch ID: $batch_id"
+  #         echo "batch_id=$batch_id" >> $GITHUB_OUTPUT
           
-      - name: Poll LAVA job status...
-        run: |
-          batch_id="${{ steps.submit.outputs.batch_id }}"
-          echo "Waiting for batch: $batch_id"
+  #     - name: Poll LAVA job status...
+  #       run: |
+  #         batch_id="${{ steps.submit.outputs.batch_id }}"
+  #         echo "Waiting for batch: $batch_id"
           
-          timeout=36000
-          start_time=$(date +%s)
+  #         timeout=36000
+  #         start_time=$(date +%s)
           
-          while true; do
-            elapsed=$(($(date +%s) - start_time))
-            if [ $elapsed -gt $timeout ]; then
-              echo "ERROR: Timeout after 10 hours"
-              exit 1
-            fi
+  #         while true; do
+  #           elapsed=$(($(date +%s) - start_time))
+  #           if [ $elapsed -gt $timeout ]; then
+  #             echo "ERROR: Timeout after 10 hours"
+  #             exit 1
+  #           fi
             
-            status_response=$(curl -s "http://${LAVA_SERVER}:${LAVA_PORT}/jobs/$batch_id/status")
-            overall_status=$(echo "$status_response" | jq -r '.overall_status // empty')
+  #           status_response=$(curl -s "http://${LAVA_SERVER}:${LAVA_PORT}/jobs/$batch_id/status")
+  #           overall_status=$(echo "$status_response" | jq -r '.overall_status // empty')
             
-            echo "Status: $overall_status"
+  #           echo "Status: $overall_status"
             
-            case "$overall_status" in
-              "success")
-                echo "All jobs completed successfully!"
-                exit 0
-                ;;
-              "failed"|"partial")
-                echo "Jobs failed or partially completed"
-                exit 1
-                ;;
-              "running")
-                sleep 30
-                ;;
-            esac
-          done
+  #           case "$overall_status" in
+  #             "success")
+  #               echo "All jobs completed successfully!"
+  #               exit 0
+  #               ;;
+  #             "failed"|"partial")
+  #               echo "Jobs failed or partially completed"
+  #               exit 1
+  #               ;;
+  #             "running")
+  #               sleep 30
+  #               ;;
+  #           esac
+  #         done
 
   # publish_images:
   #   needs: build_images
